# https://github.com/spf13/viper
# change this file to env.dev.yml

appName: "backgo"
appEnv: "dev"
appPort: 8081
jwt:
  secrets: "abcdabcd"
database:
  host: $DB_HOST
  port: 5432
  user: "db_user_here"
  name: $DB_NAME
  pass: "db_pass_here"
cloudinary:
  name: "cd_name_here"
  key: "cd_key_here"
  sec: "cd_secret_here"
